version: '3'

services:
  my_service:
    image: python:3.8
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python /app/run.py"
    volumes:
      - .:/app

    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
